### ISSUE TITLE
taking dmg but dont dies

### ISSUE THREAD

**Issue by bnjbrg** [chaseoes/TF2#52] opened 2013-10-13 21:27 UTC
hey!
problem: i hit other player, tf2 says i killed him (i also get score) but he dont actually  die he just keeps on living. his heart goes down but when his heart reaches 0 he just get healed (like he respawned but where he died). may be a compability issue.

**Comment by psycowithespn** [comment] 2014-04-12 23:42
Duplicate of https://github.com/chaseoes/TF2/issues/46

**Closed as completed by psycowithespn** 2014-04-12 23:42 UTC
